### ISSUE TITLE
Turbo compatibility, slow loading

### ISSUE THREAD

**Issue by czepesch** [railsjazz/rails_live_reload#12]
Hi there.
Thank you for the wonderful gem. But I have a problem in Rails 7 project with Turbo.

It is a very basic project (fresh one). Navbar and few static pages.
After few clicks on the links page loading takes too long. Then, it allows you to make several quick transitions, but then again the pages take a very long time to load.
When it happens - rails server logs do not respond to link clicks, like the server is freezes.

When I remove gem, everything okay.
Are there any known issues with turbo? Thanks.

**Comment by manastyretskyi** [comment]
Hi, Turbo support is not yet fully ready, so I suppose there might be some issues related to that. We have it on our roadmap, I will look into it when I have some time.

**Comment by manastyretskyi** [comment]
Now that #14 is merged I'm going to close this. Thanks for reporting it!
