### ISSUE TITLE
Can't get this gem working?

### ISSUE THREAD

**Issue by jacobperia** [railsjazz/rails_live_reload#16]
I tried this gem on a few of my projects that use HAML files, doesn't seem to be working. Did i miss something not in the documentation?
Installed the gem and then started the server. 
It shows this but doesn't do anything.
```
Watching: /Users/jake/Repos/Nurture
  (?-mix:app\/views\/.+\.(erb|haml|slim)$) => on_change
  (?-mix:(app|vendor)\/(assets|javascript)\/\w+\/(.+\.(css|js|html|png|jpg|ts|jsx)).*) => always
```
https://www.loom.com/share/a34dd1367fc849c8a6b2c4c39284cf13

**Comment by manastyretskyi** [comment]
Hello, thanks for reporting this.
I have a couple of questions:
- What version of the gem are you using?
- Does it work with css or js files?

**Comment by jacobperia** [comment]
> Hello, thanks for reporting this. I have a couple of questions:
> 
> * What version of the gem are you using?
> * Does it work with css or js files?

@manastyretskyi 
From my gemfile.lock, version
```
rails_live_reload (0.2.0)
      listen
      nio4r
      railties
      websocket-driver
```
Doesn't work with css or js files either 😕

**Comment by manastyretskyi** [comment]
Can you open a Network tab in your browser and search for a `websocket` request with path `/rails/live/reload`, please tell if there is one, and if it's active. The other thing that interests me, are there any errors in the browser console?

**Comment by jacobperia** [comment]
> Can you open a Network tab in your browser and search for a `websocket` request with path `/rails/live/reload`, please tell if there is one, and if it's active. The other thing that interests me, are there any errors in the browser console?

no websockets to be seen, just one CSS request
<img width="558" alt="image" src="https://user-images.githubusercontent.com/79951942/179266902-28c80c45-9046-4897-87f2-ab34e43aa7fc.png">

no errors in rails console. just the usual static line saying Completed 200 OK.
<img width="754" alt="image" src="https://user-images.githubusercontent.com/79951942/179267117-dc035738-cf03-41e3-ab84-f712ae78e861.png">

**Comment by manastyretskyi** [comment]
Hmm... interesting 
I wonder if `rails_live_reload` scripts are included in the page at all, can you please open an `Elements` tab and search for element like this `<script defer="" type="text/javascript" src="/rails/live/reload/script"></script>` inside a `<head>` tag?

**Comment by jacobperia** [comment]
> Hmm... interesting I wonder if `rails_live_reload` scripts are included in the page at all, can you please open an `Elements` tab and search for element like this `<script defer="" type="text/javascript" src="/rails/live/reload/script"></script>` inside a `<head>` tag?

yes that's there
<img width="552" alt="image" src="https://user-images.githubusercontent.com/79951942/179268426-80a8315b-422c-4821-b7c5-290bd0826b98.png">

**Comment by manastyretskyi** [comment]
Can you make a sample repo where this problem reproduces? So that I can debug it on my own

**Comment by jacobperia** [comment]
Here's one i just forked and cleaned up for you. Thanks.
https://github.com/jacobperia/sample-rails-app

**Comment by manastyretskyi** [comment]
Thanks for sharing this, now I know what the problem is. This is because you have a couple puma workers and one process just doesn't know about connections made by another one.
I will look into it once I have some time.

**Comment by jacobperia** [comment]
> Thanks for sharing this, now I know what the problem is. This is because you have a couple puma workers and one process just doesn't know about connections made by another one.
> I will look into it once I have some time.

Awesome ✌🏼
