### ISSUE TITLE
allow support for the holy solid trinity

### ISSUE THREAD

**Issue by thisIsLoading** [railsjazz/rails_live_reload#39]
right now this gem only seem to work with redis installed.

with rails 8 there will be solid cable / cache / queue as a replacement. 

i'd appreciate an update to support that.
thanks

**Comment by grncdr** [comment]
This gem doesn't require redis (I use it without).

**Comment by manastyretskyi** [comment]
@thisIsLoading rails_live_reload relies on it's own implementation of web sockets, so it is not dependent on redis.
